### ISSUE TITLE
Upload speakers slides

### ISSUE THREAD

**Issue by JorgeMrtnzG** [PyConColombia/landing-page-2018#101]
Currently slides are uploaded to this url:

https://drive.google.com/open?id=1Sh99sgzjAGe1LIGZ-c4maHJU078xxIAW

**Comment by JorgeMrtnzG** [comment]
modified url for slides folder:

https://drive.google.com/open?id=1fwSGnK_3RU4YWvqBWwysBIz72reTwMt1

**Comment by goanpeca** [comment]
Hey @JorgeMartinezG no tengo acceso a esa carpeta donde lo metiste. La idea es ponerlo en la carpeta `PyCon Colombia 2018 shared`, que se supone que se compartio con los correos personales

**Comment by pyjavo** [comment]
Te acabo de dar acceso @goanpeca ;)
