### ISSUE TITLE
Ocultar “Buy Tickets Now” Web Pycon 2018

### ISSUE THREAD

**Issue by leonartromo** [PyConColombia/landing-page-2018#117]
Se requiere que se oculte el Botón de "Buy Tickets Now" ya que se encuentra visible en la pagina web de PyCon Colombia 2018.

https://2018.pycon.co/

**Comment by goanpeca** [comment]
Fixed in https://github.com/PyConColombia/website-2018/commit/ec9e4c9f784a4aba3ac13c5d9c1bfa5d83aa82a0
