### ISSUE TITLE
Wrong website redirection in the mailchimp confirmation page button

### ISSUE THREAD

**Issue by jhonjairoroa87** [PyConColombia/landing-page-2018#15]
Steps to reproduce:
1. Go to pycon.co website
2. Scroll down to newsletter form
3, add a valid email and topic of interest
4. Click subscribe button
5. Check received email and click "Yes, subscribe me to this list. "
6. In the new tab that is opened verify you are not a robot and click "Subscribe to list"
7. In the "Subscription Confirmed" form do roll over / hover over the button "continue to our website" the url that is linked is "http://pyconcolombia.com/". It should be changed to www.pycon.co 
<img width="869" alt="screenshot 2017-08-01 15 17 41" src="https://user-images.githubusercontent.com/619203/28845186-cb18e97e-76cc-11e7-806e-304efa6b304b.png">

**Comment by rlaverde** [comment]
Fixed (a little change in the configurations of the mailchimp account)
