### ISSUE TITLE
Añadir voluntarios

### ISSUE THREAD

**Issue by goanpeca** [PyConColombia/landing-page-2018#84]

**Comment by Scot3004** [comment]
Sergio Orozco Torres, ya aparezco en la lista esta es la imagen
![full-color](https://user-images.githubusercontent.com/1175402/35355995-28795f6a-011d-11e8-8416-a8321225bf7c.jpg)
![imagen](https://user-images.githubusercontent.com/1175402/35356040-404d752c-011d-11e8-8eb3-2ea6e98ddb32.png)
