### ISSUE TITLE
Añadir Información de contacto Maria Camila

### ISSUE THREAD

**Issue by camigomezdev** [PyConColombia/landing-page-2018#94]
Nombre: Maria Camila Gómez Rpo
Twitter: https://twitter.com/camigomez318
Github: https://github.com/camigomez35
😄 👧 
@camigomez35

**Comment by goanpeca** [comment]
?

**Comment by camigomezdev** [comment]
Perdón, na había notado que mi información ya estaba :sweat_smile:

**Comment by goanpeca** [comment]
:-|
